tricycle_controller:
  type: tricycle_controller/TricycleController
  publish_rate: 50.0

  drive_wheel_joint: drive_wheel_joint
  steer_joint: steer_joint
  pid: {p: 0.95, i: 0.0, d: 0.15}

  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]

  cmd_vel_timeout: 25.0 # not tested here

  open_loop: false

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 0.8 # m/s
      has_acceleration_limits: true
      max_acceleration       : 0.1 # m/s^2
      min_acceleration       : -0.4
      has_jerk_limits        : true
      max_jerk               : 5.0 # m/s^3
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : !degrees 90.0
      has_acceleration_limits: true
      max_acceleration       : !degrees 90.0
      has_jerk_limits        : true
      max_jerk               : !degrees 10.0

# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
